### PR TITLE
Issue 13: Resolved the Bug

### PR DESCRIPTION
**Pull request by MrSriHarsha**
@sgoodwin - Need a little help. The bug has been resolved but there is one problem when I mark the task after searching its updating the first cell in the actual table view.

### CODE REVIEW

**Comment by sgoodwin** [comment]
Hmm, have you tried using the debugger to see the order your methods execute in? Everything looks ok, but it sounds like maybe methods aren't happening in an order you expect.

**Comment by MrSriHarsha** [comment]
Everything is working fine. When I mark a checklist as done while searching I have to make that change in checklists array too but it will be at different indexpath.

**Comment by sgoodwin** [comment]
Ah. So you maybe need both the regular list and the filtered list to use the same objects? Or to update both lists. If each item had a unique identifier, you could find them in any list, yes?

**Comment by sgoodwin** [comment]
Yay!

**Pull request merged**
